uuid = "8169e865-790e-49ff-8eff-a552697a6ce4"
name = "Soundtrack"
version = "0.1.0"
authors = ['MusicBrainz Contributors']
description = "Adds soundtrack tag for OST releases."
categories = ['metadata']
homepage = "https://github.com/musicbrainz/picard-plugins/tree/2.0/plugins/soundtrack"
report_bugs_to = "https://github.com/musicbrainz/picard-plugins/tree/2.0/plugins/soundtrack"
api = ["3.0"]
license = "GPL-2.0-or-later"
license_url = "https://www.gnu.org/licenses/gpl-2.0.html"
